"""Static mapping of subscription type codes to friendly names.

Source: Ericsson Subscription Types master table.
"""

# Maps subscription_type code -> friendly subscription name
SUBSCRIPTION_TYPE_MAP: dict[str, str] = {
    "ADV-SERVICE-ASSURACE": "Advanced Service Assurance",
    "BA-ADV-TEMP": "Temporary NetCloud Advanced Upgrade for Branch Routers",
    "BA-NCADV": "NetCloud Advanced Upgrade for Branch Routers",
    "BA-NCADV-L23": "NetCloud Extension Advanced Upgrade for Last Date of Support Branch Routers",
    "BA-NCESS": "NetCloud Essentials for Branch Routers",
    "BA-NCESSF": "NetCloud Essentials for FIPS Branch Routers",
    "BA-NCESS-L": "NetCloud Extension Essentials for Branch Routers",
    "BA-NCESS-L23": "NetCloud Extension Essentials for Last Date of Support Branch Routers",
    "BB-ADV-TEMP": "Temporary NetCloud Advanced Upgrade for LTE Adapters",
    "BB-NCADV": "NetCloud Advanced Upgrade for LTE Adapters",
    "BB-NCADV-L": "NetCloud Extension Advanced Upgrade for LTE Adapters",
    "BB-NCESS": "NetCloud Essentials for LTE Adapters",
    "BB-NCESS-L": "NetCloud Extension Essentials for LTE Adapters",
    "BC-NCESS": "NetCloud Essentials for Branch Access Points",
    "BC-NCESS-LDS": "NetCloud Essentials for Last Date of Support for Branch Access Points",
    "BD-ADV-TEMP": "Temporary NetCloud Advanced Upgrade for Branch Performance Routers",
    "BD-NCADV": "NetCloud Advanced Upgrade for Branch Performance Routers",
    "BD-NCESS": "NetCloud Essentials for Branch Performance Routers",
    "BE-ADV-TEMP": "Temporary NetCloud Advanced Upgrade for Branch 5G Adapters",
    "BE-NCADV": "NetCloud Advanced Upgrade for Branch 5G Adapters",
    "BE-NCESS": "NetCloud Essentials for Branch 5G Adapters",
    "BETA-CD": "BETA - Cellular Diagnostics",
    "BF-ADV-TEMP": "Temporary NetCloud Advanced Upgrade for Branch Enterprise Routers",
    "BF-NCADV": "NetCloud Advanced Upgrade for Branch Enterprise Routers",
    "BF-NCESS": "NetCloud Essentials for Branch Enterprise Routers",
    "BF-NCESSF": "NetCloud Essentials for FIPS Branch Enterprise Routers",
    "BGB-NCBAS": "NetCloud Basic for Branch Routers - Service Provider",
    "BG-NCADV": "NetCloud Advanced Upgrade for SMB Branch Routers",
    "BG-NCADV-SP": "NetCloud Advanced Upgrade for Branch Routers - Service Provider",
    "BG-NCCN": "NetCloud Connect",
    "BG-NCCN-LTE": "NetCloud Connect LTE",
    "BG-NCCN-PLUS": "NetCloud Connect Plus",
    "BG-NCESS": "NetCloud Essentials for SMB Branch Routers",
    "BG-NCESS-SP": "NetCloud Essentials for Branch Routers - Service Provider",
    "BH-ADV-TEMP": "Temporary NetCloud Advanced Upgrade for SOHO Branch Routers",
    "BH-NCADV": "NetCloud Advanced Upgrade for SOHO Branch Routers",
    "BH-NCADV-RUG": "NetCloud Advanced Upgrade for SOHO Ruggedized Branch Routers",
    "BH-NCESS": "NetCloud Essentials for SOHO Branch Routers",
    "BH-NCESS-RUG": "NetCloud Essentials for SOHO Ruggedized Branch Routers",
    "BK-NCADV": "NetCloud Advanced Upgrade for Small Branch Routers",
    "BK-NCADV-TEMP": "Temporary NetCloud Advanced Upgrade for Small Branch Routers",
    "BK-NCESS": "NetCloud Essentials for Small Branch Routers",
    "BK-NCESS-TRIAL": "NetCloud Essentials for Small Branch Routers Trial",
    "BL-NCADV": "NetCloud Advanced Upgrade for Branch Enterprise for E400 Routers",
    "BL-NCADV-TEMP": "Temporary NetCloud Advanced Upgrade for Branch Enterprise for E400 Routers",
    "BL-NCESS": "NetCloud Essentials for Branch Enterprise for E400 Routers",
    "BTA-AWS": "BETA - NetCloud Edge Connector for AWS IoT Greengrass",
    "BTA-CAP-DB": "BETA - Capacity Dashboard",
    "BTA-CELL": "BETA - Cellular Health",
    "BTA-CLDSRK": "BETA - CloudShark Integration",
    "BX-NCXAW": "NetCloud Essentials + Advanced for LTE Adapters",
    "CP-CLD-RTR": "CP Cloud Router",
    "CP-SEC-CON": "CP Secure Connect",
    "CP-SEC-LOC": "CP Secure Location",
    "CP-SEC-VPN": "CP Secure VPN",
    "CP-SEC-WF": "CP Secure Web Filtering",
    "CP-SEC-WFD": "CP Secure Web Filtering Demo",
    "CP-TM": "CP Secure Threat Management",
    "CRDL-CARE": "CradleCare",
    "CRDL-CARE-B": "CradleCare Basic",
    "CRDL-CARE-NCP": "Cradlecare NetCloud Perimeter Client",
    "CR-TUNNEL": "CONTROLLED RELEASE - Extended Tunnel Count",
    "CSTMR-ACCOUNT": "NetCloud Account Activation for Customers",
    "CVR-TEMP": "Temporary NetCloud Essentials for Cradlepoint Virtual Router",
    "EC-3PP-BBC": "Enterprise Cellular 3PP Baseband Connectivity",
    "EC-AR": "Enterprise Cellular for Air Radios",
    "EC-GEO-REDUN": "Enterprise Cellular Geographic Redundancy",
    "EC-HC-mmW": "Enterprise Cellular High Capacity mmWave",
    "EC-IP-RDS": "Enterprise Cellular Indoor Positioning for RDS",
    "EC-ISO-MNG": "Enterprise Cellular Isolated Management",
    "EC-LAB-CONFIG": "Enterprise Cellular Lab Configuration",
    "EC-LAB-SUPPORT": "Enterprise Cellular Lab Support",
    "EC-LOCAL-MNG": "Enterprise Cellular Local Management",
    "EC-LS": "Enterprise Cellular Local Survivability",
    "ECM-CCB": "NetCloud Manager + CradleCare Basic",
    "ECM-CCRCT": "NetCloud Manager + CradleCare",
    "EC-MC-PTT-E": "Enterprise Cellular MC-PTT Enabler",
    "ECM-ENT": "NetCloud Manager Enterprise",
    "ECM-ENT-DEMO": "NetCloud Manager Enterprise Demo",
    "EC-MIG-SUPPORT": "Enterprise Cellular Migration Support",
    "ECM-MT": "NetCloud Manager",
    "ECM-MT-OTRW": "NetCloud Manager - Outerwall",
    "ECM-PRM-CC": "NetCloud Manager Prime + CradleCare",
    "ECM-PRM-CCB": "NetCloud Manager Prime + CradleCare Basic",
    "ECM-PRM-MT": "NetCloud Manager Prime",
    "ECM-PRVT": "ECM Private",
    "EC-MS": "Enterprise Cellular Multi-Site",
    "EC-NCCE-2GBPS": "Enterprise Cellular Network Controller Capacity Expansion - 2Gbps",
    "ECRM-JSDA": "Ericom Jumpstart Deployment Assistance",
    "EC-SAS": "Enterprise Cellular Spectrum Access System",
    "EC-SDB-24/7": "Enterprise Cellular Service Desk Base 24/7",
    "EC-SYS-SC": "Enterprise Cellular Systems Support Core",
    "EC-TCC-RDS": "Enterprise Cellular TCC for RDS",
    "EEL": "EEL",
    "ENABLE-AUTOVPN": "AutoVPN Enablement",
    "ENABLE-NCP": "NetCloud Perimeter Enablement",
    "ENT-CAM-DOTS": "Enterprise Cellular Advanced Management for Dots",
    "ENT-CAM-MICRO-MACRO": "Enterprise Cellular Advanced Management for Micro/Macro",
    "ENT-CAM-NC": "Enterprise Cellular Advanced Management for Networks Controllers",
    "ENT-C-BB": "Enterprise Cellular for Baseband",
    "ENT-C-BB-TRIAL": "Enterprise Cellular for Baseband Trial",
    "ENT-C-CON": "Enterprise Cellular Consultation",
    "ENT-C-DOTS": "Enterprise Cellular for Dots",
    "ENT-C-DOTS-TRIAL": "Enterprise Cellular for Dots Trial",
    "ENT-CELL-PS": "Enterprise Cellular Professional Services",
    "ENT-C-INST": "Enterprise Cellular Installation",
    "ENT-C-IRU": "Enterprise Cellular for IRU",
    "ENT-C-IRU-TRIAL": "Enterprise Cellular for IRU Trial",
    "ENT-C-MACRO": "Enterprise Cellular for Macro Radios",
    "ENT-C-MACRO-TRIAL": "Enterprise Cellular for Macro Radios Trial",
    "ENT-C-MICRO": "Enterprise Cellular for Micro Radios",
    "ENT-C-MICRO-TRIAL": "Enterprise Cellular for Micro Radios Trial",
    "ENT-CMO-24-7": "Enterprise Cellular Managed Operations 24/7",
    "ENT-CMO-24-7-EXP": "Enterprise Cellular Managed Operations 24/7 NC Capacity Expansion",
    "ENT-CMO-8-5": "Enterprise Cellular Managed Operations 8/5",
    "ENT-CMO-8-5-EXP": "Enterprise Cellular Managed Operations 8/5 NC Capacity Expansion",
    "ENT-CMO-8-5-LITE": "Enterprise Cellular Managed Operations 8/5 Lite",
    "ENT-CMO-L": "Enterprise Cellular Managed Operations Limited",
    "ENT-C-NC-10GBPS": "Enterprise Cellular for Network Controller 10Gbps",
    "ENT-C-NC-10GBPS-TRIAL": "Enterprise Cellular for Network Controller 10Gbps Trial",
    "ENT-C-NC-15GBPS": "Enterprise Cellular for Network Controller 15Gbps",
    "ENT-C-NC-15GBPS-TRIAL": "Enterprise Cellular for Network Controller 15Gbps Trial",
    "ENT-C-NC-1GBPS": "Enterprise Cellular for Network Controller 1Gbps",
    "ENT-C-NC-1GBPS-TRIAL": "Enterprise Cellular for Network Controller 1Gbps Trial",
    "ENT-C-NC-3GBPS": "Enterprise Cellular for Network Controller 3Gbps",
    "ENT-C-NC-3GBPS-TRIAL": "Enterprise Cellular for Network Controller 3Gbps Trial",
    "ENT-C-NC-5GBPS": "Enterprise Cellular for Network Controller 5Gbps",
    "ENT-C-NC-5GBPS-TRIAL": "Enterprise Cellular for Network Controller 5Gbps Trial",
    "ENT-COV-BB": "Enterprise Coverage for Baseband",
    "ENT-COV-DOTS": "Enterprise Coverage for Dots",
    "ENT-COV-IRU": "Enterprise Coverage for IRU",
    "ENT-COV-PS": "Enterprise Coverage Professional Services",
    "ENT-COV-ROUTERS": "Enterprise Coverage for Routers",
    "ENT-COV-VQS": "Venue Qualification Service",
    "ENT-C-R": "Enterprise Cellular for Routers",
    "ENT-C-R-TRIAL": "Enterprise Cellular for Routers Trial",
    "EP5G-IDPN-EX": "Ericsson Indoor Private Network - Expansion",
    "EP5G-IDPNL-SC": "Ericsson Indoor Private Network Lab - Small Controller",
    "EP5G-ODPN-EX": "Ericsson Outdoor Private Network - Expansion",
    "EP5G-ODPN-SC": "Ericsson Outdoor Private Network - Small Controller",
    "ERCM-AAS": "Ericom Web Application Isolation",
    "ERCM-AN": "Ericom AccessNow",
    "ERCM-BLAZE": "Ericom Blaze",
    "ERCM-CONNECT": "Ericom Connect",
    "ERCM-PREM-SUPP": "Ericom Premium Support",
    "ERCM-PS": "Ericom Professional Services",
    "ERCM-PT-ES": "Ericom PowerTerm Enterprise Suite",
    "ERCM-PT-LPIC-32-BIT": "Ericom PowerTerm Lite/Plus/InterConnect 32 Bit",
    "ERCM-PT-TC": "Ericom PowerTerm Thin Client Products",
    "ERCM-PT-WCE": "Ericom PowerTerm WebConnect Enterprise",
    "ERCM-PT-WCH": "Ericom PowerTerm WebConnect Hostview",
    "ERCM-SWG": "Ericom Secure Web Gateway",
    "ERCM-WS": "Ericom Secure Web Gateway with Targeted Isolation",
    "ERCM-WSD": "Ericom Web Security DNS Over HTTPS",
    "ERCM-WSF": "Ericom Secure Web Gateway with Full Isolation",
    "ERCM-WSG": "Ericom Data Security for GenAI",
    "ERCM-ZTE-WI-HF": "Ericom ZTEdge Web Isolation Hosted Full",
    "ERCM-ZTE-WI-HT": "Ericom ZTEdge Web Isolation Hosted Targeted",
    "ERCM-ZTE-WI-OPF": "Ericom ZTEdge Web Isolation On-Prem Full",
    "ERCM-ZTE-WI-OPT": "Ericom ZTEdge Web Isolation On-Prem Targeted",
    "ERCM-ZTE-ZTNA": "Ericom ZTEdge ZTNA",
    "Ericom-ZTE-URL-C": "Ericom ZTEdge URL Categorization",
    "EXT-BF": "NetCloud Extended Tunnels",
    "EXT-BF-TRIAL": "NetCloud Extended Tunnels - Trial",
    "GRNDFTHRD": "Grandfathered Features",
    "INT-SEC-BNDL": "Internet Security Bundle",
    "INT-SEC-BNDL-P": "Internet Security Bundle Prime",
    "IOTA": "IoT Accelerator (IoTA) Connector",
    "IOT-SEC": "IoT Security",
    "ISO-NET-BRANCH": "Internet Isolated Networks Support for Branch",
    "ISO-NET-IOT": "Internet Isolated Networks Support for IoT",
    "ISO-NET-MOBILE": "Internet Isolated Networks Support for Mobile",
    "LAN-ESS-AP": "LAN Essentials for Wi-Fi AP",
    "LAN-ESS-AP-TRIAL": "LAN Essentials for Wi-Fi AP Trial",
    "LAN-ESS-SWITCH": "LAN Essentials for Switch",
    "LAN-ESS-SWITCH-TRIAL": "LAN Essentials for Switch Trial",
    "MA-ADV-TEMP": "Temporary NetCloud Advanced Upgrade for Mobile Routers",
    "MAH-NCLOC": "NetCloud Mobile Standard",
    "MA-NCADV": "NetCloud Advanced Upgrade for Mobile Routers",
    "MA-NCADV-L23": "NetCloud Extension Advanced Upgrade for Last Date of Support Mobile Routers",
    "MA-NCESS": "NetCloud Essentials for Mobile Routers",
    "MA-NCESSF": "NetCloud Essentials for FIPS Mobile Routers",
    "MA-NCESS-L23": "NetCloud Extension Essentials for Last Date of Support Mobile Routers",
    "MA-NCXLR": "NetCloud Essentials + Advanced for Mobile Routers",
    "MB-ADV-TEMP": "Temporary NetCloud Advanced Upgrade for Mobile Performance Routers",
    "MB-NCADV": "NetCloud Advanced Upgrade for Mobile Performance Routers",
    "MB-NCESS": "NetCloud Essentials for Mobile Performance Routers",
    "MB-NCESS-EXT": "NetCloud Extension Essentials for Last Date of Support Mobile Performance Routers",
    "MB-NCESSF": "NetCloud Essentials for FIPS Mobile Performance Routers",
    "MSP-QB": "MSP Quarterly Billing",
    "NC-BRANCH-DEMO": "NetCloud Essentials + Advanced Trial for Branch",
    "NCCONL": "NetCloud Connectivity",
    "NC-DM": "NetCloud Device Manager",
    "NCESS-IGT": "NetCloud Fixed IoT Essentials for IGT",
    "NC-ESS-INTEGRAT": "NetCloud Essentials + Advanced for Integrators",
    "NC-ESS-TEMP": "Temporary NetCloud Essentials",
    "NC-FED-H-AXON": "Netcloud Federal Hosted by Axon",
    "NC-FOUNDATION": "NetCloud IoT Foundation",
    "NC-FOUNDATION-ESS": "NetCloud IoT Foundation Essentials Add-On",
    "NCG": "NetCloud Gateway",
    "NCG-ST": "NetCloud Gateway Standard",
    "NC-IOT-DEMO": "NetCloud Essentials + Advanced Trial for IoT",
    "NCL-FWA": "NetCloud Link for Fixed Wireless Access",
    "NCM-API": "NCM API",
    "NC-MOBILE-DEMO": "NetCloud Essentials + Advanced Trial for Mobile",
    "NC-ODM": "NetCloud On-Site Device Manager",
    "NCP": "NetCloud Perimeter Client",
    "NCP-CLNT-STND": "NetCloud Client Standard",
    "NCP-EXT": "NCP Extension",
    "NCPN-2GBPS": "NetCloud Elastic Core - 2 Gbps",
    "NCPN-500MBPS": "NetCloud Elastic Core - 500 Mbps",
    "NCPN-5GBPS": "NetCloud Elastic Core - 5 Gbps",
    "NCPN-CELLULARAPS-TRIAL": "NetCloud Essentials for Cellular APs Trial",
    "NCPN-EC-TRIAL": "NetCloud Elastic Core Trial",
    "NCPN-MG2GBPS": "NetCloud Mobility Gateway - 2 Gbps",
    "NCPN-MG500MBPS": "NetCloud Mobility Gateway - 500 Mbps",
    "NCPN-MG5GBPS": "NetCloud Mobility Gateway - 5 Gbps",
    "NCPN-MG-TRIAL": "NetCloud Mobility Gateway Trial",
    "NCPN-SIM10": "SIM Management - NetCloud Private Networks Trial",
    "NCS-AI": "NetCloud SASE AI Insights",
    "NCS-AI-TRIAL": "NetCloud SASE AI Insights Trial",
    "NCS-DATA-CREDIT": "NetCloud SASE Data 500GB",
    "NCS-DATA-CREDIT-TRIAL": "NetCloud SASE Data 500GB - Trial",
    "NCS-DC-25GB": "NetCloud SASE Data 25GB",
    "NCS-DC-25GB-TRIAL": "NetCloud SASE Data 25GB - Trial",
    "NCS-HMF": "NetCloud SASE Hybrid Mesh Firewall",
    "NCS-HMF-TRIAL": "NetCloud SASE Hybrid Mesh Firewall Trial",
    "NCS-SC": "NetCloud SASE Secure Connect",
    "NCS-SC-LITE": "NetCloud SASE Secure Connect Lite",
    "NCS-SC-LITE-TRIAL": "NetCloud SASE Secure Connect Lite Trial",
    "NCS-SC-TRIAL": "NetCloud SASE Secure Connect Trial",
    "NCS-SDWAN": "NetCloud SASE SD-WAN",
    "NCS-SDWAN-TRIAL": "NetCloud SASE SD-WAN Trial",
    "NCS-VE": "NetCloud SASE Virtual Edge",
    "NCS-VE-TRIAL": "NetCloud SASE Virtual Edge Trial",
    "NCS-ZTNA": "NetCloud SASE ZTNA",
    "NCS-ZTNAP": "NetCloud SASE ZTNA Premium",
    "NCS-ZTNAP-TRIAL": "NetCloud SASE ZTNA Premium Trial",
    "NCS-ZTNA-TRIAL": "NetCloud SASE ZTNA Trial",
    "NC-VE": "NetCloud Essentials for Virtual Edge",
    "NC-VE-TRIAL": "NetCloud Essentials for Virtual Edge Trial",
    "NCX-AI": "NetCloud Exchange AI Insights",
    "NCX-AI-TRIAL": "NetCloud Exchange AI Insights Trial",
    "NCXH-CP500MBPS": "Internal Only Cradlepoint Hosted - 500 Mbps",
    "NCX-HMF": "NetCloud Exchange Hybrid Mesh Firewall",
    "NCX-HMF-L": "NetCloud Exchange Hybrid Mesh Firewall - Large Site",
    "NCX-HMF-M": "NetCloud Exchange Hybrid Mesh Firewall - Medium Site",
    "NCX-HMF-MS": "NetCloud Exchange Hybrid Mesh Firewall - Micro Site",
    "NCX-HMF-SS": "NetCloud Exchange Hybrid Mesh Firewall - Small Site",
    "NCX-HMF-TRIAL": "NetCloud Exchange Hybrid Mesh Firewall Trial",
    "NCXH-SG500MBPS": "Hosted NetCloud Exchange Service Gateway - 500 Mbps",
    "NCXH-SG500MBPS-TRIAL": "Hosted NetCloud Exchange Service Gateway - 500 Mbps - Trial",
    "NCX-NCSG": "NetCloud Exchange Service Gateway",
    "NCX-NCSG-250MBPS": "NetCloud Exchange Service Gateway - 250 Mbps",
    "NCX-NCSG-500MB": "NetCloud Exchange Service Gateway - 500 Mbps",
    "NCX-NCSG-SC": "NetCloud Service Gateway with Secure Connectivity",
    "NCX-NCSG-TEMP": "NetCloud Exchange Service Gateway Trial",
    "NCX-NCVG": "NetCloud VPN Gateway",
    "NCX-NCVG-TEMP": "NetCloud VPN Gateway Trial",
    "NCX-SC": "NetCloud Exchange Secure Connect",
    "NCX-SCIOT": "NetCloud Exchange Secure Connect - Micro Site",
    "NCX-SCL": "NetCloud Exchange Secure Connect - Large Site",
    "NCX-SCM": "NetCloud Exchange Secure Connect - Medium Site",
    "NCX-SCS": "NetCloud Exchange Secure Connect - Small Site",
    "NCX-SC-TEMP": "NetCloud Exchange Secure Connect Trial",
    "NCX-SC-TRIAL": "NetCloud Exchange Secure Connect Trial",
    "NCX-SDWAN": "NetCloud Exchange SD-WAN",
    "NCX-SD-WAN": "NetCloud Exchange SD-WAN",
    "NCX-SDWANL": "NetCloud Exchange SD-WAN - Large Site",
    "NCX-SDWANM": "NetCloud Exchange SD-WAN - Medium Site",
    "NCX-SDWANMICRO": "NetCloud Exchange SD-WAN - Micro Site",
    "NCX-SDWANS": "NetCloud Exchange SD-WAN - Small Site",
    "NCX-SDWAN-TRIAL": "NetCloud Exchange SD-WAN Trial",
    "NCX-VE": "NetCloud Exchange Virtual Edge",
    "NCX-VE-TRIAL": "NetCloud Exchange Virtual Edge Trial",
    "NCX-ZTNA": "NetCloud Exchange ZTNA",
    "NCX-ZTNAC1": "NetCloud Exchange Zero Trust Network Access - 1 Client",
    "NCX-ZTNAC10": "NetCloud Exchange Zero Trust Network Access - 10 Clients",
    "NCX-ZTNAC100": "NetCloud Exchange Zero Trust Network Access - 100 Clients",
    "NCX-ZTNAC5": "NetCloud Exchange Zero Trust Network Access - 5 Clients",
    "NCX-ZTNAC50": "NetCloud Exchange Zero Trust Network Access - 50 Clients",
    "NCX-ZTNA-TRIAL": "NetCloud Exchange ZTNA Trial",
    "NC-ZSCALER": "Zscaler Internet Security",
    "NEMO": "NEMO",
    "NET-MON-SEC-BNDL": "Network Management Security Bundle",
    "NON-COMPLIANT": "Non-Compliant NetCloud Devices",
    "PA-NCESS": "NetCloud Essentials for Indoor Cellular APs",
    "PB-NCESS": "NetCloud Essentials for Outdoor Cellular APs",
    "PISO-NET": "Permanent Internet Isolated Networks",
    "PRTNR-ACCOUNT": "NetCloud Account Activation for Partners",
    "RMA-TDNCESS": "NetCloud Essentials for Private Cellular Networks",
    "R-SDK": "Router SDK",
    "SA-SIM10": "SIM Management - NetCloud Private Networks",
    "SEC-NCIWF": "NetCloud IPS and Web Filter Security",
    "SIM-EP5G": "SIM Management - Ericsson Private 5G",
    "SIM-EP5G-TRIAL": "SIM Management - Ericsson Private 5G Trial",
    "SIMETRIC-50": "SIM Management - Simetric Connector",
    "SIMETRIC-50-TRIAL": "SIM Management - Simetric Connector Trial",
    "TA-NCADV": "NetCloud Advanced Upgrade for IoT",
    "TA-NCADV-L23": "NetCloud Extension Advanced Upgrade for Last Date of Support IoT",
    "TA-NCESS": "NetCloud Essentials for IoT",
    "TA-NCESS-L23": "NetCloud Extension Essentials for Last Date of Support IoT",
    "TB-ADV-TEMP": "Temporary NetCloud Advanced Upgrade for IoT",
    "TBF-NCCON": "NetCloud Connectivity for IoT",
    "TBF-NCCONL-TRIAL": "NetCloud Connectivity for IoT Trial",
    "TBF-NCESS": "NetCloud IoT Essentials Add-on",
    "TBF-NCESS-LIMITED": "TRIAL NetCloud Limited Essentials for IoT",
    "TC-ADV-TEMP": "Temporary NetCloud Advanced Upgrade for Ruggedized IoT",
    "TC-NCADV": "NetCloud Advanced Upgrade for Ruggedized IoT",
    "TC-NCESS": "NetCloud Essentials for Ruggedized IoT",
    "TD-ADV-TEMP": "Temporary NetCloud Advanced Upgrade for Private Cellular Networks",
    "TD-NCADV": "NetCloud Advanced Upgrade for Private Cellular Networks",
    "TD-NCESS": "NetCloud Essentials for Private Cellular Networks",
    "test-ir": "TEST-IR-11",
    "TK-NCADV": "NetCloud Advanced Upgrade for IoT Fixed Location Routers",
    "TK-NCADV-TEMP": "Temporary NetCloud Advanced Upgrade for IoT Fixed Location Routers",
    "TK-NCESS": "NetCloud Essentials for IoT Fixed Location Routers",
    "TX-NCXRB": "NetCloud Essentials + Advanced for IoT",
    "UNFD-TM-BNDL": "Unified Threat Management Bundle",
    "UNFD-TM-BNDL-P": "Unified Threat Management Bundle Prime",
    "VA-CVRADV": "NetCloud Advanced Upgrade for Cradlepoint Virtual Router",
    "VA-CVRESS": "NetCloud Essentials for Cradlepoint Virtual Router",
    "WAR-EXT": "Warranty Extension",
    "WPC": "WPC",
    # Legacy aliases
    "BF03-NCESS": "NetCloud Essentials for Branch Enterprise Routers",
    "BF03-NCADV": "NetCloud Advanced Upgrade for Branch Enterprise Routers",
    "NCX-VESC-TRIAL": "NetCloud Exchange Virtual Edge Secure Connect Trial",
    "NCX-SG-TRIAL": "NetCloud Exchange Service Gateway Trial",
    "NCS-DC-TRIAL": "NetCloud SASE Data Credits Trial",
}

# Subscription names to exclude from the Software Licenses tab
EXCLUDED_SUBSCRIPTIONS: set[str] = {
    "ECM-API-1YR",
    "NON-COMPLIANT",
}

# Subscription name prefixes for pool/software-based licenses where
# per-device assignment data is not available from the API.
# Only ZTNA and Data Credit subscriptions are pool-based.
POOL_SUBSCRIPTION_PREFIXES: tuple[str, ...] = (
    "NCS-ZTNA",
    "NCS-ZTNAP",
    "NCS-DATA-CREDIT",
    "NCS-DC-",
    "NCX-ZTNA",
    "ERCM-ZTE-ZTNA",
)


def is_pool_subscription(name: str | None) -> bool:
    """Return True if this subscription is pool/software-based (no per-device assignment)."""
    if not name:
        return False
    return any(name.startswith(p) for p in POOL_SUBSCRIPTION_PREFIXES)


def resolve_subscription_type(code: str | None) -> str | None:
    """Look up a friendly name for a subscription type code.

    Returns the friendly name if found, or the original code if not.
    Returns None if code is None.
    """
    if code is None:
        return None
    return SUBSCRIPTION_TYPE_MAP.get(code, code)
